module.exports = {
  tutorialSidebar: [
    "README",
    {
      type: "category",
      label: "Overview",
      link: { type: "generated-index", title: "Overview" },
      items: [{ type: "autogenerated", dirName: "overview" }],
    },
    {
      type: "category",
      label: "Architecture",
      link: { type: "generated-index", title: "Architecture" },
      items: [{ type: "autogenerated", dirName: "architecture" }],
    },
    {
      type: "category",
      label: "Platform",
      link: { type: "generated-index", title: "Platform" },
      items: [{ type: "autogenerated", dirName: "platform" }],
    },

    // ✅ Dynamic domains
    {
      type: "category",
      label: "Domains",
      link: { type: "generated-index", title: "Domains" },
      items: [{ type: "autogenerated", dirName: "domains" }],
    },

    {
      type: "category",
      label: "Setup",
      link: { type: "generated-index", title: "Setup" },
      items: [{ type: "autogenerated", dirName: "setup" }],
    },
    {
      type: "category",
      label: "Old",
      collapsed: true,
      items: [{ type: "autogenerated", dirName: "old" }],
    },
  ],
};
